### ISSUE TITLE
Add option to copy downloads instead of using symlinks when creating the mirror

### ISSUE THREAD

**Issue by Blockguy24** [montag451/pypi-mirror#11]
Relevant code:
https://github.com/montag451/pypi-mirror/blob/87f440e61c9369ce5dbb251fc3f379e746f1d05d/pypi_mirror.py#L280-L285

**Comment by montag451** [comment]
Hi @Blockguy24,

I added a new option to copy packages instead of symlinking them (see aeef83c). If it fits your needs I will release a new version on PyPI soon.

**Comment by Blockguy24** [comment]
Yeah, this looks good. Thanks for implementing this.
