### ISSUE TITLE
Add --no-build-isolation option

### ISSUE THREAD

**Issue by ddormer** [montag451/pypi-mirror#15]
I'm having problems downloading the `cryptography` package due to cyclic build dependencies, this is also a problem running pip directly with `pip download cryptography --no-binary ":all:"`.

For this case it would be great to be able to pass the `--no-build-isolation` flag to pip from pypi-mirror to to use my user environment that contains the correct build dependencies.

**Comment by montag451** [comment]
Hi @ddormer,

I've added a `--no-build-isolation` option to the `download` command in 490364d. Let me known if it solves your problem and if it is OK for you I will publish a new version on PyPi.

**Comment by ddormer** [comment]
Thanks for the quick reply! The flag seems to work perfectly for me and solves my problem :)

**Comment by montag451** [comment]
I published a new release on [PyPI](https://pypi.org/project/python-pypi-mirror/4.2.0/) which contain the new option you requested. Thank you for the issue report!
