### ISSUE TITLE
fails to create a local mirror for torch package

### ISSUE THREAD

**Issue by onixlas** [montag451/pypi-mirror#17]
Hi. I'm trying to create a local mirror for torch package:

~/.local/bin/pypi-mirror --print-traceback download -d dowloads torch
ERROR: Could not find a version that satisfies the requirement torch
ERROR: No matching distribution found for torch
Failed to execute command 'download': Command '['pip', 'download', '-d', 'dowloads', '--no-binary', ':all:', 'torch']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/xinm/.local/lib/python3.9/site-packages/pypi_mirror.py", line 773, in main
    cmd.run(args)
  File "/home/xinm/.local/lib/python3.9/site-packages/pypi_mirror.py", line 553, in run
    download_(pkgs, args.requirements)
  File "/home/xinm/.local/lib/python3.9/site-packages/pypi_mirror.py", line 219, in download
    subprocess.check_call(args)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'download', '-d', 'dowloads', '--no-binary', ':all:', 'torch']' returned non-zero exit status 1.

Debian GNU/Linux stable
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
Python 3.9.2

**Comment by montag451** [comment]
Hi @onixlas,

You should try to use the `-b` flag of the `download` command.

**Comment by montag451** [comment]
No news is good news :smiley:

**Comment by adamryczkowski** [comment]
Yes, it works for me, thank you!
