### ISSUE TITLE
Windows: create mirror Failed to execute command 'create': symbolic link privilege not held

### ISSUE THREAD

**Issue by duaneellissd** [montag451/pypi-mirror#19]
simular to: https://github.com/montag451/pypi-mirror/issues/11

This crashes on windows, and this feature would be nice - how can I invoke this option on windows?
HELP does not help in this reguard.

Thanks.

**Comment by montag451** [comment]
Did you try to use `--copy` when creating the mirror?

**Comment by montag451** [comment]
No news is good news!
