### ISSUE TITLE
Error: metadata file not found

### ISSUE THREAD

**Issue by dacevedo12** [montag451/pypi-mirror#21]
`Failed to execute command 'create': error while processing '/path/Hypercorn-0.14.3-py3-none-any.whl': metadata file not found`

https://files.pythonhosted.org/packages/be/8b/e856965857137bc594e8fd52fef1d00b79913a6a01033cba772276aff10b/Hypercorn-0.14.3-py3-none-any.whl

I've tracked it down to the `get_metadata_from_wheel` function, which doesn't seem to consider casing.

this dependency was published to pypi as hypercorn (lower case) but the wheel file is Hypercorn (uppercase h). Weirdly enough, the directories inside the wheel are lowercase, which causes the error

**Comment by montag451** [comment]
Thx for the bug report. I pushed a new commit 5659998 that should solve your problem. Let me know if it's OK for you.

**Comment by dacevedo12** [comment]
Awesome, thanks!

Will a new version be released including this fix anytime soon? I'll update it on https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/pypi-mirror/default.nix

**Comment by montag451** [comment]
I've published a new release (5.0.2) on PyPI

**Comment by dacevedo12** [comment]
would it be possible to update the tag in the repo too? There's a bot on nixpkgs looking for tags to notice the update

Sorry to bother and thanks a lot for this great library!

**Comment by montag451** [comment]
Done! Thx for the reminder, usually I tag every release but this time I forgot...
