### ISSUE TITLE
Adding pypi-mirror to conda-forge

### ISSUE THREAD

**Issue by ethanwhite** [montag451/pypi-mirror#22]
Thanks for this great package @montag451! We're using it to help support teaching data science in areas with limited internet access - https://github.com/carpentriesoffline/offlinedatasci/.

We're working on supporting package installation of `offlinedatasci` via [conda-forge](https://conda-forge.org/) and doing that requires that pypi-mirror can also be installed that way.

Doing this requires a little bit of work in a separate repository that creates a simple YAML recipe to allow conda-forge to build the conda package (using the source from PyPI; [see the docs](https://conda-forge.org/docs/maintainer/adding_pkgs.html#creating-recipes)). This is something anyone can do, it doesn't need to be the package maintainer, and my group maintains several conda-forge recipes for dependencies for our projects. We'd be happy to do that for pypi-mirror, but we always like to reach out to the primary developers to see if they would rather setup and maintain this infrastructure themselves.

So, is this something you'd be interested in doing or working with us on? If not would you be OK with us doing it (with zero commitment to  anything on your end)?

**Comment by montag451** [comment]
Hi @ethanwhite,

Happy to know that my package is useful for you :) I'm perfectly OK with you submitting a recipe for my package to conda-forge.

**Comment by montag451** [comment]
Can I close the issue or do you prefer to keep it open as long as the recipe is not on conda-forge?

**Comment by ethanwhite** [comment]
Closing is fine (I'll do it now). The PR is just waiting on review at conda-forge: https://github.com/conda-forge/staged-recipes/pull/22112

Once it's up I'll submit a PR for you to consider if you want to add conda install instructions to the README.

**Comment by montag451** [comment]
> Closing is fine (I'll do it now). The PR is just waiting on review at conda-forge: https://github.com/conda-forge/staged-recipes/pull/22112
> 
> Once it's up I'll submit a PR for you to consider if you want to add conda install instructions to the README.

👍
