### ISSUE TITLE
Add --extra-index-url option

### ISSUE THREAD

**Issue by lukashenneke** [montag451/pypi-mirror#23]
Hello,

Thank you very much for your nice project, it is much appreciated!

I have problems downloading a GPU version of pytorch as it is not hosted on [pypi.org](https://pypi.org/project/torch) but on [download.pytorch.org](https://download.pytorch.org/whl/torch).
Using the `--index` option with `https://download.pytorch.org/whl/cu116` will cause errors as the requirements (available on pypi) cannot be found.
For this case, it would be great if you could pass the `--extra-index-url` option to pip from pypi-mirror.

Many thanks in advance!

**Comment by montag451** [comment]
Hi @lukashenneke,

I added the --extra-index-url option to the download command (on the master branch). Can you test it? If it's OK for you I will publish a new version on PyPi.

**Comment by lukashenneke** [comment]
Hello @montag451,

I just tested the new option on different platforms, it works as expected. A new version on PyPi that includes the changes would be great!

Thank you very much!

**Comment by montag451** [comment]
@lukashenneke I've published a new release on PyPI (v5.1.0). Thx again for your bug report!
