### ISSUE TITLE
ERROR: No matching distribution found for twmap

### ISSUE THREAD

**Issue by ChillerDragon** [montag451/pypi-mirror#28]
```
$ ./pypi_mirror.py  download twmap -d data
ERROR: Could not find a version that satisfies the requirement twmap (from versions: none)
ERROR: No matching distribution found for twmap
Failed to execute command 'download': Command '['python', '-m', 'pip', 'download', '-d', 'data', '--no-binary', ':all:', 'twmap']' returned non-zero exit status 1.
To get further information re-run the script with --print-traceback
```

While this one works
```
$ python -m pip install twmap
Collecting twmap
  Using cached twmap-0.4.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Installing collected packages: twmap
Successfully installed twmap-0.4.3
```

And twmap is just an example here. I had the issue with many packages.
Seems like the ``--no-binary :all:`` fails the install for most of the wheel packages on my system.
Can this be dropped or does it break the mirror?

**Comment by montag451** [comment]
Hi @ChillerDragon,

Sorry for the late reply. You have to use `-b` option to download a binary distribution (e.g a wheel) :
``` python
pypi-mirror download -d data -b twmap
```

**Comment by ChillerDragon** [comment]
> Hi @ChillerDragon,
> 
> 
> 
> Sorry for the last reply. You have to use `-b` option to download a binary distribution (e.g a wheel) :
> 
> ``` python
> 
> pypi-mirror download -d data -b twmap
> 
> ```

Why is that not active by default? Is there some catch?

**Comment by montag451** [comment]
I don't remember why I made this the default behavior but obviously it was the wrong choice. I plan to change this in the next major release (6.0.0) but for the moment you will have to use the `-b` option :(

**Comment by ChillerDragon** [comment]
> I don't remember why I made this the default behavior but obviously it was the wrong choice. I plan to change this in the next major release (6.0.0) but for the moment you will have to use the `-b` option :(

Wonderful thanks
