### ISSUE TITLE
Get n last versions

### ISSUE THREAD

**Issue by m4nch0t** [montag451/pypi-mirror#3]
Hi,
First, thank you for your work. I want to know if we could get the n last versions of package, this feature exist in bandersnatch (but it doesn't manage dependency with whitelist).

**Comment by montag451** [comment]
Hi @m4nch0t,

I'm not sure I understand what you are asking for. Do you want to be able to execute something like that:
``` bash
pypi-mirror -d my_download_dir download --last-n-versions 3 the_package_i_want
```
to download the last 3 versions of a package?

**Comment by m4nch0t** [comment]
Hi,

Yes, exactly. Some packages (like ansible) evoluate quickly and we don't have so much time to adapt. I don't want to keep very old versions (why I don't prefer to specify version number), so teams have to get close to roadmap.

**Comment by montag451** [comment]
I see `pypi-mirror` as a toolbox to manage PyPI mirrors. Each command must be simple and can be used to build more complex commands. In this spirit, I decided to not complexify the `download` command but instead I added a new command that let you query the PyPI index to retrieve the latest versions of a package. With a bit of scripting, you can now achieve what you want. For example, the following command downloads the latest 3 versions of `ansible` :
``` bash
pypi-mirror query -l 3 ansible | while read version; do pypi-mirror download -d my_download_dir ansible==$version; done 
```
If you want to keep only the latest 3 versions of `ansible` in your mirror, you can use the following command:
```bash
pypi-mirror delete -d my_download_dir -m my_mirror_dir -k 3 ansible
```
Be aware that the `delete` command does not delete the dependencies of a package.

**Comment by m4nch0t** [comment]
Thank you so much for your work, and I agree with you let's keep it simple.
I've now a error with download but I think it's my venv, I will troubleshoot it later.
`Failed to execute command 'download': 'Namespace' object has no attribute 'pkgs'`

> Be aware that the delete command does not delete the dependencies of a package.

Off course that's why my mirror will be rebuild automatically and frequently

**Comment by montag451** [comment]
> Failed to execute command 'download': 'Namespace' object has no attribute 'pkgs'

Oh you are right there was a typo in my code, thank you. I uploaded a new version of the package on PyPI (version 4.0.1)

**Comment by montag451** [comment]
If the new command fits your need I will close this issue

**Comment by m4nch0t** [comment]
Hi,
Quite busy this day. I've just give a try and it seems good, thank you!

**Comment by montag451** [comment]
You are welcome! Feel free to reopen this issue if you found out something wrong with the new command.
