### ISSUE TITLE
python 3.12, removed distutils

### ISSUE THREAD

**Issue by MichaelRiss** [montag451/pypi-mirror#30]
I tried running pypi-mirror on a Fedora 39 with a python 3.12 venv and I get this error:

```
Traceback (most recent call last):
  File "<censored>/pypienv-python3.12/bin/pypi-mirror", line 5, in <module>
    from pypi_mirror import main
  File "<censored>/pypienv-python3.12/lib64/python3.12/site-packages/pypi_mirror.py", line 7, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
```

Is seems in python 3.12 the `distutils` module is removed: https://peps.python.org/pep-0632/

Only having superficial python packaging knowledge I don't know what this means for the pypi-mirror project. Does it "just" require a fix? Or does this change remove the basis of how this project interacts with the packages and will the project disappear with python 3.12?

**Comment by montag451** [comment]
Hi @MichaelRiss,

I've published a [new version](https://pypi.org/project/python-pypi-mirror/5.2.1/) on PyPI which make `pypi_mirror` compatible with Python 3.12. Let me know if the new version fixes your problem :)

**Comment by MichaelRiss** [comment]
Hello @montag451 
Thank you for the quick response. It does fix my immediate problem of downloading and creating the mirror. I have not tested using it yet as our deployment environment has not caught up to python 3.12 so far (I'm a bit ahead of the curve with my mirror). But it's looking very good so far, thank you!

**Comment by montag451** [comment]
Thx for you feedback, I will close the issue but feel free to reopen it if you discover a problem with the fix
