### ISSUE TITLE
Re-use existing pip cache

### ISSUE THREAD

**Issue by jayvdb** [montag451/pypi-mirror#5]
Fetching the packages from the existing pip cache can avoid refetching content fetched prior to using this server.

The pip wheel cache includes raw whl files which can be simply symlinked into the new pypare storage. The pip http cache is a bit trickier, but I was able to do batch import of sdists at jerith/landinggear#3

**Comment by montag451** [comment]
Not sure to understand what you are asking for.

**Comment by montag451** [comment]
Closing this ticket as I'm not sure you know what this project is about. Feel free to re-open it if I'm wrong
