### ISSUE TITLE
HTTPS request support

### ISSUE THREAD

**Issue by Spriithy** [montag451/pypi-mirror#6]
Hi,

is there any plan on introducing HTTPS requests support for this projet ?

Thanks in advance

**Comment by montag451** [comment]
Hi,

What do you mean by "introducing HTTPS requests support"? I think there is maybe an misunderstanding about what this project is about. This project lets you create a partial PyPI mirror (by partial I mean with only the packages you use). This mirror can then be served by whatever webserver you like (Apache, NGINX). This project has nothing to do with a project like [pypiserver](https://pypi.org/project/pypiserver/), it's more like a lightweight version of [bandersnatch](https://pypi.org/project/bandersnatch/).

**Comment by Spriithy** [comment]
Yeah, right. For a second I thought idk why that https was handled on the server's code but nah. I managed to bring nginx on my network and set this up working.

By the way, I really dig the ease of use of your project. I compiled a little guide on how to setup a mirror on an isolated network [See here](https://github.com/Spriithy/doc/blob/master/PyPi_Mirroring.md). It's cool !
