### ISSUE TITLE
Looking for pip instead of pip3

### ISSUE THREAD

**Issue by johnbrannstrom** [montag451/pypi-mirror#8]
On Centos 8 i got the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'pip': 'pip'`

I solved it with the following:
`ln -s /usr/bin/pip3 /usr/bin/pip`

I'm on version:
```
pip3 show python-pypi-mirror
Name: python-pypi-mirror
Version: 4.0.3
```

**Comment by montag451** [comment]
Hi @johnbrannstrom 

You can use the option `-p` (or `--pip-executable`) to specify the pip you want to use:
```bash
pypi-mirror download -p pip3 requests
```

**Comment by montag451** [comment]
I will close this issue as I think my previous message answers your question. Feel free to open a new issue if it is not the case.
