### ISSUE TITLE
Questions about maintaining the partial mirror

### ISSUE THREAD

**Issue by linuxdan** [montag451/pypi-mirror#9]
After initially setting up my mirror,  when new versions of packages are released, what is the recommended way to update the mirror ?
Can the update optionally (retain or remove) older versions ?

**Comment by montag451** [comment]
To update packages you can use the download command, it will fetch the latest version of the specified packages. If you want to update all your packages you can use this command (on GNU/Linux):
```sh
pypi-mirror list -d /path/to/my/download/dir --name-only | xargs pypi-mirror download -d /path/to/my/download/dir
```
Older versions of the package will not be removed.

**Comment by linuxdan** [comment]
Thanks for a quick response.
Is there much activity/overhead if there is nothing new ?

**Comment by linuxdan** [comment]
Almost forgot: Do you need to re-run the "create" command for an update ?

**Comment by montag451** [comment]
> Thanks for a quick response.
> Is there much activity/overhead if there is nothing new ?

Under the wood `pypi-mirror` uses `pip` to download packages so I can't tell you how work much is done by `pip` when there is nothing new but it must be only a few requests sent to `PyPI`

**Comment by montag451** [comment]
> Almost forgot: Do you need to re-run the "create" command for an update ?

Yes

**Comment by linuxdan** [comment]
That covers my questions.
Many thanks
